export const inputStyle = {
       appearance: "none",
       backgroundColor: "#fff",
       backgroundImage: "none",
       borderRadius: "4px",
       border: "1px solid #bfcbd9",
       boxSizing: "border-box",
       color: "#1f2d3d",
       fontSize: "inherit",
       height: "36px",
       lineHeight: "1",
       outline: "0",
       padding: "3px 10px",
       width: "100%",
       transition: "border-color .2s cubic-bezier(.645,.045,.355,1)",
       marginTop: "10px",
  }

export const buttonStyle = {
    width: "100%",
    display: "inline-block",
    lineHeight: "1",
    whiteSpace: "nowrap",
    cursor: "pointer",
    background: "#fff",
    border: "1px solid #c4c4c4",
    borderTopColor: "rgb(196, 196, 196)",
    borderRightColor: "rgb(196, 196, 196)",
    borderBottomColor: "rgb(196, 196, 196)",
    borderLeftColor: "rgb(196, 196, 196)",
    color: "#1f2d3d",
    margin: "0",
    padding: "10px 15px",
    borderRadius: "4px",
    marginTop: "10px",
  }
